### ISSUE TITLE
Stream connector tutorial - for MIMO fluid blocks?

### ISSUE THREAD

**Issue by RSchiemann** [justnielsen/ModelicaTutorials#2]
Hi,

I have yet another request. Could you please provide a minimum working example for a fluid model using stream connectors, which does the following:

- has three input flows
- has two output flows
- output flow 1 = 0.25 * Input flow 1 + 0.5 * Input flow 2 + 0.75 * Input flow 3
- output flow 2 = 0.75 * Input flow 1 + 0.5 * Input flow 2 + 0.25 * Input flow 3
- energy balance according to input flow distribution

I tried myself but have not achieved to develop a simulating model. It seems to me that the above is not fully in line with the stream concept, is that correct?

Best regards,
Robert

**Comment by RSchiemann** [comment]
One addition: The pressure drop across this component shall be zero (or close to zero, if that helps).

**Comment by justnielsen** [comment]
Hello Robert,

Sorry about my very late reply.

What you're after is probably very common: an ad hoc manipulation of fluids. What is really important to consider is "how can this be made with real physical components and controllers?".

I've added a few examples to the library in a sub-package called MIMO. I'll probably rename it later to something with "control" since the issue is really about controlling certain thermo-fluid quantities (e.g. mass flow).

But for now I hope the examples will help you...

BR Rene
